### ISSUE TITLE
[Exception] `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by amaridev** [AtomMaterialUI/material-theme-ui-lite#188]
**Describe the bug**
IntelliJ throws an Exception because of Material Theme UI Lite (23.0.0). 

**Environment**
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.intellij.laf.enable.animation=true
Non-Bundled Plugins:
  com.mallowigi.idea (23.0.0)
  org.jetbrains.plugins.go-template (241.14494.150)
  Pythonid (241.14494.314)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
Kotlin: 241.14494.240-IJ

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.mallowigi.idea.themes.ActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.mallowigi.idea]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by mallowigi** [comment]
closing this for now, if it happens again, let's create a new issue
